import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { BaselimeRum } from "@baselime/react-rum";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-Poppins">
      <script src="./node_modules/preline/dist/preline.js"></script>
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet"
      />
      <body className={`font-Poppins`}>
        <BaselimeRum
          apiKey={process.env.NEXT_PUBLIC_BASELIME_API_KEY as string}
          enableWebVitals
          fallback={<h1>An error occured</h1>}
        >
          <Providers>{children}</Providers>
        </BaselimeRum>
      </body>
    </html>
  );
}
